#!/bin/bash
set -xe

ROOT=$(pwd)

#deploy function

cd generator
gcloud functions deploy generator \
      --runtime python37 \
      --region=europe-west1 \
      --trigger-topic function_trigger_topic \
      --entry-point main --verbosity=debug

cd $ROOT

